# -*- coding: utf-8 -*-
"""GTSDB (Hog + HSV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzElWOKrBevCKoBGT4XcGn9j32QUWdKq
"""

from google.colab import drive
drive.mount('/content/drive')

import kagglehub

path = kagglehub.dataset_download("safabouguezzi/german-traffic-sign-detection-benchmark-gtsdb")
print("Downloaded to:", path)

TRAIN_DIR   = '/kaggle/input/german-traffic-sign-detection-benchmark-gtsdb/TrainIJCNN2013/TrainIJCNN2013/'

TEST_DIR    = '/kaggle/input/german-traffic-sign-detection-benchmark-gtsdb/TestIJCNN2013/TestIJCNN2013Download/'
GT_DIR    = '/kaggle/input/german-traffic-sign-detection-benchmark-gtsdb/kaggle/input/gtsrb-german-traffic-sign/gt.txt'

from PIL import Image
import matplotlib.pyplot as plt

# Đường dẫn file
path = TRAIN_DIR + '00000.ppm'

# Mở ảnh
img = Image.open(path)

# Hiển thị
plt.imshow(img)
plt.axis('off')

import torch
from PIL import Image
import shutil
import os
from random import choice
import numpy as np
import pandas as pd
import cv2



# Kích thước mục tiêu cho ảnh được resize
target_size = (32, 32)

# 1. Đọc file nhãn gt.txt
try:
    df = pd.read_csv(os.path.join(TRAIN_DIR, 'gt.txt'), sep=';', header=None,
                     names=['filename', 'x1', 'y1', 'x2', 'y2', 'class_id'])
    print("Đã đọc file gt.txt thành công.")
except FileNotFoundError:
    print(f"Lỗi: Không tìm thấy file gt.txt tại {os.path.join(TRAIN_DIR, 'gt.txt')}")
    print("Vui lòng kiểm tra lại đường dẫn tới file gt.txt.")
    exit()

df

import matplotlib.pyplot as plt
import cv2
import os
from random import choice

# Ensure CLASS_NAMES is available for displaying labels
CLASS_NAMES = {
    0:'Speed limit (20)',    1:'Speed limit (30)',   2:'Speed limit (50)',
    3:'Speed limit (60)',    4:'Speed limit (70)',   5:'Speed limit (80)',
    6:'End speed limit(80)', 7:'Speed limit (100)',  8:'Speed limit (120)',
    9:'No passing',         10:'No passing >3.5t',  11:'Right-of-way',
    12:'Priority road',     13:'Yield',              14:'Stop',
    15:'No vehicles',       16:'No >3.5t vehicles', 17:'No entry',
    18:'General caution',   19:'Danger curve left', 20:'Danger curve right',
    21:'Double curve',      22:'Bumpy road',         23:'Slippery road',
    24:'Road narrows',      25:'Road work',          26:'Traffic signals',
    27:'Pedestrians',       28:'Children crossing',  29:'Bicycles crossing',
    30:'Ice/snow',          31:'Wild animals',       32:'End speed+passing',
    33:'Turn right ahead',  34:'Turn left ahead',    35:'Ahead only',
    36:'Go straight/right', 37:'Go straight/left',   38:'Keep right',
    39:'Keep left',         40:'Roundabout',          41:'End no passing',
    42:'End no passing >3.5t'
}

print("Đang chuẩn bị hiển thị ảnh mẫu với bounding box...")

# 1. Chọn một ảnh ngẫu nhiên từ DataFrame
# Lấy danh sách các tên file ảnh duy nhất
unique_filenames = df['filename'].unique()

if len(unique_filenames) == 0:
    print("Lỗi: Không tìm thấy bất kỳ file ảnh nào trong DataFrame.")
else:
    # Chọn ngẫu nhiên một tên file
    random_filename = choice(unique_filenames)
    image_path = os.path.join(TRAIN_DIR, random_filename)

    # 2. Đọc ảnh
    img = cv2.imread(image_path)
    if img is None:
        print(f"Lỗi: Không thể đọc ảnh từ {image_path}. Vui lòng kiểm tra đường dẫn hoặc tính toàn vẹn của file.")
    else:
        # Chuyển đổi từ BGR (OpenCV) sang RGB (Matplotlib)
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # 3. Lấy tất cả các bounding box cho ảnh này từ DataFrame
        image_annotations = df[df['filename'] == random_filename]

        # 4. Vẽ các bounding box lên ảnh
        img_with_boxes = img_rgb.copy() # Tạo một bản sao để vẽ

        for index, row in image_annotations.iterrows():
            x1, y1, x2, y2, class_id = int(row['x1']), int(row['y1']), int(row['x2']), int(row['y2']), int(row['class_id'])

            # Vẽ hình chữ nhật
            # Màu xanh lá cây (Green) trong RGB: (0, 255, 0)
            color = (0, 255, 0)
            thickness = 2
            cv2.rectangle(img_with_boxes, (x1, y1), (x2, y2), color, thickness)

            # Thêm nhãn lớp
            class_name = CLASS_NAMES.get(class_id, f"Class {class_id}") # Lấy tên lớp hoặc mặc định
            font = cv2.FONT_HERSHEY_SIMPLEX
            font_scale = 1
            font_thickness = 2
            text_size = cv2.getTextSize(class_name, font, font_scale, font_thickness)[0]

            # Đặt văn bản phía trên bounding box
            text_x = x1
            text_y = y1 - 10 if y1 - 10 > 10 else y1 + text_size[1] + 10 # Tránh tràn viền
            cv2.putText(img_with_boxes, class_name, (text_x, text_y), font, font_scale, color, font_thickness, cv2.LINE_AA)

        # 5. Hiển thị ảnh với matplotlib
        plt.figure(figsize=(15, 10))
        plt.imshow(img_with_boxes)
        plt.title(f'Ảnh: {random_filename} với các Bounding Box và Nhãn')
        plt.axis('off') # Tắt trục tọa độ
        plt.show()

        print(f"Đã hiển thị ảnh '{random_filename}' với {len(image_annotations)} biển báo được gắn nhãn.")

# 2. Hàm Toán học: calculate_iou(boxA, boxB)
def calculate_iou(boxA, boxB):
    # Xác định tọa độ của hình chữ nhật giao nhau
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])

    # Tính diện tích hình chữ nhật giao nhau
    interArea = max(0, xB - xA + 1) * max(0, yB - yA + 1)

    # Tính diện tích của cả hai hình chữ nhật
    boxAArea = (boxA[2] - boxA[0] + 1) * (boxA[3] - boxA[1] + 1)
    boxBArea = (boxB[2] - boxB[0] + 1) * (boxB[3] - boxB[1] + 1)

    # Tính IoU
    iou = interArea / float(boxAArea + boxBArea - interArea)

    # Trả về giá trị IoU
    return iou

# Khởi tạo danh sách chứa các mẫu
pos_images = []
neg_images = []

print("Bắt đầu trích xuất Positive Samples...")
# 3. Trích xuất Positive Samples (Nhãn 1)
# Duyệt qua từng nhóm filename để xử lý các bounding box trong cùng một ảnh
grouped = df.groupby('filename')

for filename, group in grouped:
    image_path = os.path.join(TRAIN_DIR, filename)
    try:
        img = cv2.imread(image_path)
        if img is None:
            print(f"Cảnh báo: Không thể đọc ảnh {image_path}. Bỏ qua.")
            continue
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # Chuyển BGR sang RGB
    except Exception as e:
        print(f"Lỗi khi tải ảnh {image_path}: {e}. Bỏ qua.")
        continue

    for index, row in group.iterrows():
        x1, y1, x2, y2 = int(row['x1']), int(row['y1']), int(row['x2']), int(row['y2'])

        # Đảm bảo tọa độ hợp lệ
        h, w, _ = img.shape
        x1 = max(0, x1)
        y1 = max(0, y1)
        x2 = min(w, x2)
        y2 = min(h, y2)

        # Cắt vùng ảnh
        cropped_img = img[y1:y2, x1:x2]

        # Kiểm tra xem vùng cắt có hợp lệ không (không rỗng)
        if cropped_img.shape[0] > 0 and cropped_img.shape[1] > 0:
            # Resize về kích thước (32, 32)
            resized_img = cv2.resize(cropped_img, target_size)
            pos_images.append(resized_img)

print(f"Đã trích xuất {len(pos_images)} Positive Samples.")

pos_images[9]

print("Bắt đầu trích xuất Negative Samples...")
# 4. Trích xuất Negative Samples (Nhãn 0 - Background)
num_positive_samples = len(pos_images)
num_negative_samples_target = num_positive_samples * 2
current_negative_samples = 0

# Lấy danh sách các tên file ảnh duy nhất từ dataframe
unique_filenames = df['filename'].unique()

for filename in unique_filenames:
    if current_negative_samples >= num_negative_samples_target:
        break

    image_path = os.path.join(TRAIN_DIR, filename)
    try:
        img = cv2.imread(image_path)
        if img is None:
            print(f"Cảnh báo: Không thể đọc ảnh {image_path} cho mẫu âm. Bỏ qua.")
            continue
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    except Exception as e:
        print(f"Lỗi khi tải ảnh {image_path} cho mẫu âm: {e}. Bỏ qua.")
        continue

    h, w, _ = img.shape

    # Lấy các hộp giới hạn dương (positive bounding boxes) trong ảnh này
    positive_boxes_in_image_df = df[df['filename'] == filename][['x1', 'y1', 'x2', 'y2']]
    positive_boxes_in_image = positive_boxes_in_image_df.values.astype(int)

    attempts_per_image = 500  # Giới hạn số lần thử tạo hộp ngẫu nhiên mỗi ảnh
    for _ in range(attempts_per_image):
        if current_negative_samples >= num_negative_samples_target:
            break

        # Tạo hộp giới hạn ngẫu nhiên (kích thước từ 30x30 đến 100x100)
        box_width = np.random.randint(30, 101)
        box_height = np.random.randint(30, 101)

        # Đảm bảo hộp ngẫu nhiên không vượt quá kích thước ảnh
        if box_width >= w or box_height >= h:
            continue

        x1_rand = np.random.randint(0, w - box_width)
        y1_rand = np.random.randint(0, h - box_height)
        x2_rand = x1_rand + box_width
        y2_rand = y1_rand + box_height
        random_box = (x1_rand, y1_rand, x2_rand, y2_rand)

        # Tính IoU của hộp ngẫu nhiên với tất cả các hộp dương trong ảnh
        max_iou = 0.0
        if len(positive_boxes_in_image) > 0:
            for p_box in positive_boxes_in_image:
                max_iou = max(max_iou, calculate_iou(random_box, p_box))

        # Nếu IoU tối đa < 0.1, đây là một mẫu âm
        if max_iou < 0.1:
            cropped_neg_img = img[y1_rand:y2_rand, x1_rand:x2_rand]

            if cropped_neg_img.shape[0] > 0 and cropped_neg_img.shape[1] > 0:
                resized_neg_img = cv2.resize(cropped_neg_img, target_size)
                neg_images.append(resized_neg_img)
                current_negative_samples += 1

print(f"Đã trích xuất {len(neg_images)} Negative Samples.")

# 5. Đóng gói: Gộp các mẫu thành mảng numpy
X_binary = np.array(pos_images + neg_images)
y_binary = np.array([1] * len(pos_images) + [0] * len(neg_images))

print(f"Shape của X_binary: {X_binary.shape}")
print(f"Shape của y_binary: {y_binary.shape}")

neg_images[0]

np.save('/content/gt.npy', df)
np.save('/content/pos_images.npy', pos_images)
np.save('/content/neg_images.npy', neg_images)

# !cp /content/gt.npy /content/drive/MyDrive/gtsrb_dataset/
# !cp /content/pos_images.npy /content/drive/MyDrive/gtsrb_dataset/
# !cp /content/neg_images.npy /content/drive/MyDrive/gtsrb_dataset/

import numpy as np

pos_image = np.load('/content/drive/MyDrive/gtsrb_dataset/pos_images.npy')
neg_image = np.load('/content/drive/MyDrive/gtsrb_dataset/neg_images.npy')

from sklearn.model_selection import train_test_split
from skimage.feature import hog
from skimage.color import rgb2gray
import matplotlib.pyplot as plt
import numpy as np

# 1. Chia dữ liệu
X_train_bin, X_test_bin, y_train_bin, y_test_bin = train_test_split(
    X_binary, y_binary, test_size=0.2, stratify=y_binary, random_state=42
)

print(f"Shape của X_train_bin: {X_train_bin.shape}")
print(f"Shape của y_train_bin: {y_train_bin.shape}")
print(f"Shape của X_test_bin: {X_test_bin.shape}")
print(f"Shape của y_test_bin: {y_test_bin.shape}")

# 2. Trực quan hóa HOG (Visualization)

# Chọn ra 1 ảnh Positive và 1 ảnh Negative ngẫu nhiên từ X_train_bin
pos_indices = np.where(y_train_bin == 1)[0]
neg_indices = np.where(y_train_bin == 0)[0]

if len(pos_indices) > 0 and len(neg_indices) > 0:
    random_pos_idx = np.random.choice(pos_indices)
    random_neg_idx = np.random.choice(neg_indices)

    pos_image = X_train_bin[random_pos_idx]
    neg_image = X_train_bin[random_neg_idx]

    # Chuyển sang Grayscale
    pos_image_gray = rgb2gray(pos_image)
    neg_image_gray = rgb2gray(neg_image)

    # Áp dụng HOG với visualize=True
    _, hog_image_pos = hog(pos_image_gray, orientations=9, pixels_per_cell=(8, 8),
                           cells_per_block=(2, 2), visualize=True, feature_vector=False)
    _, hog_image_neg = hog(neg_image_gray, orientations=9, pixels_per_cell=(8, 8),
                           cells_per_block=(2, 2), visualize=True, feature_vector=False)

    # Trực quan hóa
    plt.figure(figsize=(10, 8))

    plt.subplot(2, 2, 1)
    plt.imshow(pos_image)
    plt.title('Ảnh gốc Positive')
    plt.axis('off')

    plt.subplot(2, 2, 2)
    plt.imshow(hog_image_pos, cmap='gray')
    plt.title('Ảnh HOG Positive')
    plt.axis('off')

    plt.subplot(2, 2, 3)
    plt.imshow(neg_image)
    plt.title('Ảnh gốc Negative')
    plt.axis('off')

    plt.subplot(2, 2, 4)
    plt.imshow(hog_image_neg, cmap='gray')
    plt.title('Ảnh HOG Negative')
    plt.axis('off')

    plt.tight_layout()
    plt.show()
else:
    print("Không đủ mẫu dương hoặc âm để trực quan hóa HOG.")


# 3. Trích xuất hàng loạt (Feature Extraction)
def extract_hog_features(images):
    features = []
    for img in images:
        # Chuyển sang Grayscale
        gray_img = rgb2gray(img)
        # Trích xuất đặc trưng HOG
        hog_features = hog(gray_img, orientations=9, pixels_per_cell=(8, 8),
                           cells_per_block=(2, 2), feature_vector=True)
        features.append(hog_features)
    return np.array(features)

# Áp dụng hàm cho tập huấn luyện và kiểm tra
print("\nĐang trích xuất đặc trưng HOG cho X_train_bin...")
X_train_hog = extract_hog_features(X_train_bin)
print("Đang trích xuất đặc trưng HOG cho X_test_bin...")
X_test_hog = extract_hog_features(X_test_bin)

# In ra shape của mảng HOG
print(f"\nShape của X_train_hog: {X_train_hog.shape}")
print(f"Shape của X_test_hog: {X_test_hog.shape}")

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import time

scaler = StandardScaler()
X_train_svm_bin = scaler.fit_transform(X_train_hog)
X_test_svm_bin = scaler.transform(X_test_hog)

print("Đã chuẩn hóa dữ liệu cho SVM.")
print(f"Shape của X_train_svm_bin: {X_train_svm_bin.shape}")
print(f"Shape của X_test_svm_bin: {X_test_svm_bin.shape}")

# GridSearchCV toàn diện để tìm siêu tham số tốt nhất

# Khởi tạo mô hình cơ sở
svm_model = SVC(class_weight='balanced', random_state=42)

# Định nghĩa param_grid
# Tách riêng param_grid cho 'linear' và 'rbf' kernel vì gamma chỉ áp dụng cho 'rbf'
param_grid = [
    {'kernel': ['linear'],
     'C': [0.1, 1, 10]
     },
    {'kernel': ['rbf'],
     'C': [0.1, 1, 10],
     'gamma': ['scale', 0.01, 0.001]},
    {'kernel': ['poly'],
     'C': [0.1, 1],
     'degree': [2, 3],
     'gamma': ['scale']},
    {'kernel': ['sigmoid'],
     'C': [0.1, 1],
     'gamma': ['scale']}
]

# Khởi tạo GridSearchCV
grid_search = GridSearchCV(svm_model, param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=2)

print("\nBắt đầu tìm kiếm siêu tham số với GridSearchCV...")
start_time = time.time()

# Fit GridSearchCV
grid_search.fit(X_train_svm_bin, y_train_bin)

end_time = time.time()
fitting_time = end_time - start_time
print(f"Tìm kiếm siêu tham số hoàn tất sau {fitting_time:.2f} giây.")



# Đánh giá mô hình tốt nhất

print("\nCác tham số tốt nhất tìm được:", grid_search.best_params_)

# Lấy mô hình tốt nhất
best_svm_model = grid_search.best_estimator_

# Dự đoán trên tập kiểm tra
y_pred_bin = best_svm_model.predict(X_test_svm_bin)

# In ra các chỉ số đánh giá
print("\nAccuracy Score trên tập kiểm tra:", accuracy_score(y_test_bin, y_pred_bin))
print("\nClassification Report trên tập kiểm tra:\n", classification_report(y_test_bin, y_pred_bin))

# In Ma trận nhầm lẫn (Confusion Matrix)
cm = confusion_matrix(y_test_bin, y_pred_bin)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Negative (0)', 'Positive (1)'],
            yticklabels=['Negative (0)', 'Positive (1)'])
plt.title('Ma trận nhầm lẫn cho SVM nhị phân')
plt.xlabel('Dự đoán')
plt.ylabel('Thực tế')
plt.show()

results_df = pd.DataFrame(grid_search.cv_results_)

# Chỉ lấy các cột được yêu cầu
columns_to_display = [
    'param_kernel', 'param_C', 'param_gamma', 'param_degree',
    'mean_test_score', 'std_test_score', 'mean_fit_time'
]

# Kiểm tra và thêm các cột nếu chúng tồn tại (gamma, degree chỉ có với một số kernel)
actual_columns = [col for col in columns_to_display if col in results_df.columns]
filtered_results_df = results_df[actual_columns]

# Sắp xếp bảng theo mean_test_score giảm dần
filtered_results_df = filtered_results_df.sort_values(by='mean_test_score', ascending=False)

print("Top 10 cấu hình tốt nhất:")
display(filtered_results_df.head(10))

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from random import choice

def propose_bounding_boxes(image_path):
    img_bgr = cv2.imread(image_path)
    if img_bgr is None:
        return [], None

    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    image_height, image_width, _ = img_rgb.shape

    # =======================================================
    # CHIẾN THUẬT 4: TIỀN XỬ LÝ ÁNH SÁNG BẰNG CLAHE
    # =======================================================
    # Chuyển sang không gian LAB để tách riêng kênh Sáng (L) và kênh Màu (A, B)
    lab = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)

    # Áp dụng CLAHE để kéo sáng các vùng bóng râm (như mép đường có cây)
    clahe = cv2.createCLAHE(clipLimit=2.5, tileGridSize=(8, 8))
    l_eq = clahe.apply(l)

    # Gộp lại và chuyển về RGB
    img_enhanced = cv2.cvtColor(cv2.merge((l_eq, a, b)), cv2.COLOR_LAB2RGB)

    # =======================================================
    # CHIẾN THUẬT 5: TOÁN HỌC NORMALIZED RGB R/(R+G+B)
    # =======================================================
    # Chuyển kiểu float để tính toán không bị tràn số lượng
    R = img_enhanced[:,:,0].astype(np.float32)
    G = img_enhanced[:,:,1].astype(np.float32)
    B = img_enhanced[:,:,2].astype(np.float32)

    # Cộng thêm 1e-6 để tránh lỗi chia cho 0 (ZeroDivisionError)
    Sum = R + G + B + 1e-6

    norm_R = R / Sum
    norm_B = B / Sum

    # Tạo Mask (Mặt nạ):
    # Biển cấm (Đỏ): Tỉ lệ đỏ > 40% VÀ cường độ pixel đỏ không quá đen (>30)
    # Biển hiệu lệnh (Xanh): Tỉ lệ xanh > 40% VÀ cường độ pixel xanh không quá đen (>30)
    red_mask = np.uint8((norm_R > 0.40) & (R > 30)) * 255
    blue_mask = np.uint8((norm_B > 0.40) & (B > 30)) * 255

    final_mask = cv2.bitwise_or(red_mask, blue_mask)

    # Dùng hình thái học Morphological (Close/Open) để nối liền các mảng màu bị rách
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    final_mask = cv2.morphologyEx(final_mask, cv2.MORPH_CLOSE, kernel)
    final_mask = cv2.morphologyEx(final_mask, cv2.MORPH_OPEN, kernel)

    # =======================================================
    # CHIẾN THUẬT 2: LỌC RÁC THEO HÌNH HỌC (SHAPE-BASED)
    # =======================================================
    contours, _ = cv2.findContours(final_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    boxes = []
    for c in contours:
        x, y, w, h = cv2.boundingRect(c)
        area = w * h
        aspect_ratio = float(w) / h

        # Điều kiện khắt khe:
        # 1. Diện tích phải đủ lớn (> 200 pixel) để nhìn rõ
        # 2. Tỷ lệ khung hình từ 0.6 đến 1.4 (Loại bỏ các vệt màu dài ngoằng hoặc dẹt)
        if 200 < area < 16000 and 0.4 < aspect_ratio < 1.9:
            boxes.append((x, y, w, h))

    return boxes, img_rgb

def propose_bounding_boxes_hybrid(image_path):
    img_bgr = cv2.imread(image_path)
    if img_bgr is None:
        return [], None

    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    image_height, image_width, _ = img_rgb.shape

    # 1. TIỀN XỬ LÝ (CLAHE và Grayscale cho MSER)
    gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    gray_eq = clahe.apply(gray)

    # 2. CHUẨN BỊ BẢN ĐỒ MÀU NORMALIZED RGB (Để kiểm duyệt)
    img_float = img_rgb.astype(np.float32)
    R = img_float[:,:,0]
    G = img_float[:,:,1]
    B = img_float[:,:,2]
    Sum = R + G + B + 1e-6

    norm_R = R / Sum
    norm_B = B / Sum

    # 3. CHẠY MSER TÌM HÌNH KHỐI
    mser = cv2.MSER_create(delta=5, min_area=150, max_area=15000)
    regions, boundingBoxes = mser.detectRegions(gray_eq)

    # Lọc box trùng lặp nhanh
    boundingBoxes = cv2.groupRectangles(boundingBoxes.tolist(), groupThreshold=1, eps=0.2)[0]

    final_boxes = []

    for box in boundingBoxes:
        x, y, w, h = box
        aspect_ratio = float(w) / h

        # A. Lọc hình học (Chỉ lấy hình tương đối vuông/tròn)
        if 0.7 <= aspect_ratio <= 1.3:

            # B. Lọc màu sắc (Kiểm duyệt chéo)
            # Lấy vùng trung tâm của box để check màu (tránh lấy viền)
            cx, cy = x + w//2, y + h//2
            check_w, check_h = int(w * 0.5), int(h * 0.5)
            rx1, ry1 = max(0, cx - check_w//2), max(0, cy - check_h//2)
            rx2, ry2 = min(image_width, rx1 + check_w), min(image_height, ry1 + check_h)

            roi_norm_R = norm_R[ry1:ry2, rx1:rx2]
            roi_norm_B = norm_B[ry1:ry2, rx1:rx2]

            # Tính trung bình tỷ lệ Đỏ và Xanh trong vùng này
            mean_red = np.mean(roi_norm_R) if roi_norm_R.size > 0 else 0
            mean_blue = np.mean(roi_norm_B) if roi_norm_B.size > 0 else 0

            # Nếu tỷ lệ Đỏ > 35% HOẶC Xanh > 35%, ta mới chấp nhận nó là biển báo
            if mean_red > 0.1 or mean_blue > 0.1:

                # C. [HACK PADDING] Bơm thêm 30% diện tích và ép hình vuông chuẩn
                box_size = int(max(w, h) * 1.3)

                new_x1 = max(0, cx - box_size // 2)
                new_y1 = max(0, cy - box_size // 2)
                new_x2 = min(image_width, new_x1 + box_size)
                new_y2 = min(image_height, new_y1 + box_size)

                real_w = new_x2 - new_x1
                real_h = new_y2 - new_y1

                final_boxes.append((new_x1, new_y1, real_w, real_h))

    return final_boxes, img_rgb

def bounding_boxes_3(image_path):
    img_bgr = cv2.imread(image_path)
    if img_bgr is None:
        return [], None

    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    # 1. Chuyển sang HSV và Cân bằng sáng (CLAHE) trên kênh Value (V)
    hsv = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2HSV)
    h, s, v = cv2.split(hsv)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    v_eq = clahe.apply(v)
    hsv_eq = cv2.merge((h, s, v_eq))

    # 2. Lọc màu Đỏ và Xanh (Ngưỡng S > 70, V > 50)
    lower_red1 = np.array([0, 70, 50])
    upper_red1 = np.array([10, 255, 255])
    lower_red2 = np.array([160, 70, 50])
    upper_red2 = np.array([180, 255, 255])
    lower_blue = np.array([100, 70, 50])
    upper_blue = np.array([130, 255, 255])

    mask_red1 = cv2.inRange(hsv_eq, lower_red1, upper_red1)
    mask_red2 = cv2.inRange(hsv_eq, lower_red2, upper_red2)
    mask_blue = cv2.inRange(hsv_eq, lower_blue, upper_blue)

    raw_binary_mask = mask_red1 | mask_red2 | mask_blue

    # 3. Hình thái học (Dọn rác hạt tiêu)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    filtered_mask = cv2.morphologyEx(raw_binary_mask, cv2.MORPH_CLOSE, kernel)
    filtered_mask = cv2.morphologyEx(filtered_mask, cv2.MORPH_OPEN, kernel)

    # 4. Tìm Contours và Lọc Hình học
    contours, _ = cv2.findContours(filtered_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    boxes = []
    for c in contours:
        x, y, w, h = cv2.boundingRect(c)
        area = w * h
        aspect_ratio = float(w) / h

        # Áp dụng thông số chuẩn
        if 200 < area < 16000 and 0.4 < aspect_ratio < 1.9:
            boxes.append((x, y, w, h))

    return boxes, img_rgb

# --- Demo Function ----
# Chọn ngẫu nhiên 1 file ảnh .ppm từ thư mục TRAIN_DIR

all_ppm_files = [f for f in os.listdir(TEST_DIR) if f.endswith('.ppm')]
if not all_ppm_files:
    print(f"Không tìm thấy file .ppm nào trong thư mục {TRAIN_DIR}")
else:
    random_image_filename = choice(all_ppm_files)
    random_image_path = os.path.join(TEST_DIR, random_image_filename)

    print(f"Đang xử lý ảnh: {random_image_path}")

    # Gọi hàm propose_bounding_boxes
    proposed_boxes, original_image_rgb = propose_bounding_boxes(random_image_path)

    if original_image_rgb is not None:
        # Vẽ các bounding boxes lên ảnh gốc
        image_with_boxes = original_image_rgb.copy()
        for (x, y, w, h) in proposed_boxes:
            cv2.rectangle(image_with_boxes, (x, y), (x + w, y + h), (255, 255, 0), 2) # Màu vàng, độ dày 2

        # Hiển thị ảnh với matplotlib
        plt.figure(figsize=(12, 8))
        plt.imshow(image_with_boxes)
        plt.title(f'Ảnh gốc với các Bounding Box đề xuất cho biển báo ({len(proposed_boxes)} boxes)')
        plt.axis('off')
        plt.show()

        print(f"Đã tìm thấy {len(proposed_boxes)} bounding box đề xuất.")
    else:
        print("Không thể xử lý ảnh hoặc ảnh không hợp lệ.")

from skimage.color import rgb2gray
from skimage.feature import hog
import cv2
import matplotlib.pyplot as plt

# Kiểm tra xem random_image_path đã được định nghĩa chưa, nếu chưa thì tạo lại
if 'random_image_path' not in locals() or not os.path.exists(random_image_path):
    print("random_image_path không tồn tại hoặc không hợp lệ, đang chọn lại ảnh...")
    all_ppm_files = [f for f in os.listdir(TEST_DIR) if f.endswith('.ppm')]
    if not all_ppm_files:
        print(f"Không tìm thấy file .ppm nào trong thư mục {TRAIN_DIR}")
        exit()
    random_image_filename = choice(all_ppm_files)
    random_image_path = os.path.join(TEST_DIR, random_image_filename)

print(f"Đang xử lý ảnh: {random_image_path}")

# 1. Gọi hàm propose_bounding_boxes(image_path)
proposed_boxes, original_image_rgb = propose_bounding_boxes_hybrid(random_image_path)

if original_image_rgb is None:
    print(f"Lỗi: Không thể tải hoặc xử lý ảnh từ {random_image_path}")
else:
    # 2. Tạo một bản sao của ảnh gốc để vẽ kết quả
    result_img = original_image_rgb.copy()

    print(f"Số lượng boxes được đề xuất bởi OpenCV: {len(proposed_boxes)}")

    # 3. Lặp qua từng box trong danh sách
    for (x, y, w, h) in proposed_boxes:
        # Đảm bảo tọa độ hợp lệ và không vượt quá kích thước ảnh
        img_h, img_w, _ = original_image_rgb.shape
        x1, y1 = max(0, x), max(0, y)
        x2, y2 = min(img_w, x + w), min(img_h, y + h)

        # Cắt vùng ảnh đó ra từ ảnh gốc
        cropped_roi = original_image_rgb[y1:y2, x1:x2]

        # Kiểm tra xem vùng cắt có hợp lệ không (không rỗng)
        if cropped_roi.shape[0] > 0 and cropped_roi.shape[1] > 0:
            # Resize vùng cắt về (32, 32)
            resized_roi = cv2.resize(cropped_roi, target_size)

            # Chuyển sang Grayscale
            gray_roi = rgb2gray(resized_roi)

            # Dùng skimage.feature.hog để trích xuất vector 324 chiều
            # (Đảm bảo block_norm='L2-Hys' giống lúc train)
            hog_features = hog(gray_roi, orientations=9, pixels_per_cell=(8, 8),
                               cells_per_block=(2, 2), feature_vector=True, block_norm='L2-Hys')

            # Dùng scaler để chuẩn hóa vector HOG này
            scaled_hog_features = scaler.transform(hog_features.reshape(1, -1))

            # Đưa vào binary_svm.predict() để dự đoán
            prediction = best_svm_model.predict(scaled_hog_features)

            # Trực quan hóa:
            if prediction == 0:  # Negative/Rác
                # Vẽ bounding box màu ĐỎ (Red) lên result_img với độ dày = 2 (trong RGB)
                cv2.rectangle(result_img, (x, y), (x + w, y + h), (255, 0, 0), 2)
            else:  # Positive/Biển báo
                # Vẽ bounding box màu XANH LÁ (Green) lên result_img với độ dày = 4 (trong RGB)
                cv2.rectangle(result_img, (x, y), (x + w, y + h), (0, 255, 0), 4)
                # Ghi thêm text "Traffic Sign" ở trên hộp
                cv2.putText(result_img, 'Traffic Sign', (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

    # Dùng matplotlib hiển thị result_img
    plt.figure(figsize=(15, 10))
    plt.imshow(result_img)
    plt.title(f'Kết quả phát hiện biển báo sau khi lọc SVM cho ảnh: {os.path.basename(random_image_path)}')
    plt.axis('off')
    plt.show()

import joblib

joblib.dump(best_svm_model, '/content/drive/MyDrive/gtsrb_dataset/detect_model.pkl')

joblib.dump(scaler, '/content/drive/MyDrive/gtsrb_dataset/detect_scaler.pkl')

import joblib

best_svm_model = joblib.load('/content/drive/MyDrive/gtsrb_dataset/detect_model.pkl')

import joblib
from tensorflow.keras.models import load_model

final_hybrid_svm = joblib.load('/content/drive/MyDrive/gtsrb_dataset/final_hybrid_svm.pkl')
cnn_feature_extractor = load_model('/content/drive/MyDrive/gtsrb_dataset/cnn_feature_extractor.h5')
svm_scaler = joblib.load('/content/drive/MyDrive/gtsrb_dataset/svm_scaler.pkl')
detect_scaler = joblib.load('/content/drive/MyDrive/gtsrb_dataset/detect_scaler.pkl')

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from random import choice
from skimage.color import rgb2gray
from skimage.feature import hog


CLASS_NAMES = {
    0:'Speed limit (20)',    1:'Speed limit (30)',   2:'Speed limit (50)',
    3:'Speed limit (60)',    4:'Speed limit (70)',   5:'Speed limit (80)',
    6:'End speed limit(80)', 7:'Speed limit (100)',  8:'Speed limit (120)',
    9:'No passing',         10:'No passing >3.5t',  11:'Right-of-way',
    12:'Priority road',     13:'Yield',              14:'Stop',
    15:'No vehicles',       16:'No >3.5t vehicles', 17:'No entry',
    18:'General caution',   19:'Danger curve left', 20:'Danger curve right',
    21:'Double curve',      22:'Bumpy road',         23:'Slippery road',
    24:'Road narrows',      25:'Road work',          26:'Traffic signals',
    27:'Pedestrians',       28:'Children crossing',  29:'Bicycles crossing',
    30:'Ice/snow',          31:'Wild animals',       32:'End speed+passing',
    33:'Turn right ahead',  34:'Turn left ahead',    35:'Ahead only',
    36:'Go straight/right', 37:'Go straight/left',   38:'Keep right',
    39:'Keep left',         40:'Roundabout',          41:'End no passing',
    42:'End no passing >3.5t'
}

# --- 2. Define recognize_traffic_signs_in_scene function ---
# The models (final_hybrid_svm, cnn_feature_extractor, svm_scaler, best_svm_model)
# and scalers (scaler for HOG features) are assumed to be loaded globally
# from previous executed cells (Z1utpt74rqmO and 1NsC17UTrWx1).

def recognize_traffic_signs_in_scene(image_path, iou_threshold_nms=0.3):
    print(f"Bắt đầu xử lý ảnh: {image_path}")

    # a. Gọi hàm đề xuất vùng
    proposed_boxes_xywh, original_image_rgb = propose_bounding_boxes_hybrid(image_path)

    if original_image_rgb is None:
        print(f"Lỗi: Không thể tải hoặc xử lý ảnh từ {image_path}")
        return

    result_image = original_image_rgb.copy()
    image_height, image_width, _ = original_image_rgb.shape

    detected_boxes = []
    detection_scores = []

    print(f"  Phát hiện: Đang kiểm tra {len(proposed_boxes_xywh)} hộp đề xuất...")
    # b. Vòng lặp HOG + Binary SVM (Có Hack Padding)
    for (x, y, w, h) in proposed_boxes_xywh:

        # --- [HACK TẠO KHOẢNG ĐỆM VÀ ÉP VUÔNG] ---
        center_x = x + w // 2
        center_y = y + h // 2

        # Lấy cạnh lớn nhất, cộng thêm 30% padding để lấy được bối cảnh xung quanh
        box_size = int(max(w, h) * 1.3)

        # Tính toán tọa độ mới
        x1 = max(0, center_x - box_size // 2)
        y1 = max(0, center_y - box_size // 2)
        x2 = min(image_width, x1 + box_size)
        y2 = min(image_height, y1 + box_size)

        # Tính lại w, h thực tế (phòng trường hợp hộp bị cắt ở mép ảnh)
        real_w = x2 - x1
        real_h = y2 - y1
        # -----------------------------------------

        cropped_roi = original_image_rgb[y1:y2, x1:x2]

        if cropped_roi.shape[0] > 0 and cropped_roi.shape[1] > 0:
            resized_roi = cv2.resize(cropped_roi, (32, 32))
            gray_roi = rgb2gray(resized_roi)

            # Trích xuất đặc trưng HOG
            hog_features = hog(gray_roi, orientations=9, pixels_per_cell=(8, 8),
                               cells_per_block=(2, 2), feature_vector=True, block_norm='L2-Hys')

            # Scale bằng biến detect_scaler của mô hình nhị phân (324 chiều)
            scaled_hog_features = detect_scaler.transform(hog_features.reshape(1, -1))

            # BỎ HÀM PREDICT MẶC ĐỊNH. Tính trực tiếp điểm khoảng cách Margin:
            decision_score = best_svm_model.decision_function(scaled_hog_features)[0]

            # Hạ ngưỡng kiểm duyệt xuống -0.2 (Biển báo hơi mờ/méo vẫn qua được)
            if decision_score > -0.2:
                # Phải lưu lại [x1, y1, real_w, real_h] của hộp MỚI (đã có padding)
                detected_boxes.append([x1, y1, real_w, real_h])
                # Shift scores to be positive for NMSBoxes, while preserving relative order
                detection_scores.append(decision_score + 0.21) # Add a small constant to make scores > 0

    print(f"  Phát hiện: Đã tìm thấy {len(detected_boxes)} hộp dương tính trước NMS.")

    detected_boxes_np = np.array(detected_boxes, dtype=np.int32)
    detection_scores_np = np.array(detection_scores, dtype=np.float32)

    final_indices = []
    if len(detected_boxes_np) > 0:
        # --- [SỬA LỖI TÀNG HÌNH CỦA OPENCV] ---
        # score_threshold phải >= 0. Chúng ta đã shift detection_scores_np lên trên 0.
        indices = cv2.dnn.NMSBoxes(detected_boxes_np.tolist(), detection_scores_np.tolist(),
                                   score_threshold=0.0, nms_threshold=iou_threshold_nms) # Changed to 0.0
        if len(indices) > 0:
            final_indices = indices.flatten()

    final_boxes = []
    final_labels = []
    final_detection_scores = []

    print(f"  NMS: {len(final_indices)} hộp vượt qua NMS.")

    # e. Nhận diện (CNN + SVM Đa lớp)
    for i in final_indices:
        x, y, w, h = detected_boxes_np[i]
        # The original decision_score (before shifting) might be useful if needed later
        # For display, we can use the shifted score or recalculate if needed
        score_detection = detection_scores_np[i]

        x1, y1 = max(0, x), max(0, y)
        x2, y2 = min(image_width, x + w), min(image_height, y + h)

        cropped_roi_recognition = original_image_rgb[y1:y2, x1:x2]

        if cropped_roi_recognition.shape[0] > 0 and cropped_roi_recognition.shape[1] > 0:
            resized_roi_recognition = cv2.resize(cropped_roi_recognition, (32, 32))
            normalized_roi = resized_roi_recognition.astype("float32") / 255.0
            expanded_roi = np.expand_dims(normalized_roi, axis=0)

            cnn_features = cnn_feature_extractor.predict(expanded_roi, verbose=0)
            scaled_cnn_features = svm_scaler.transform(cnn_features)

            class_id = final_hybrid_svm.predict(scaled_cnn_features)[0]
            class_name = CLASS_NAMES.get(class_id, f"Unknown Sign ({class_id})")

            final_boxes.append((x, y, w, h))
            final_labels.append(class_name)
            # When storing final_detection_scores, you might want to store the original decision_score
            # or clarify that this is the shifted score used for NMS.
            # For now, let's keep the shifted score to reflect the NMS confidence.
            final_detection_scores.append(score_detection)

    print(f"  Nhận diện: Đã nhận diện {len(final_boxes)} biển báo cuối cùng.")

    for (x, y, w, h), label in zip(final_boxes, final_labels):
        color = (0, 255, 0)
        thickness = 3
        cv2.rectangle(result_image, (x, y), (x + w, y + h), color, thickness)
        cv2.putText(result_image, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)

    plt.figure(figsize=(15, 10))
    plt.imshow(result_image)
    plt.title(f'Phát hiện và Nhận diện biển báo cho ảnh: {os.path.basename(image_path)}')
    plt.axis('off')
    plt.show()

    return final_boxes, final_labels, final_detection_scores

# --- 3. Chạy thử hàm này với một bức ảnh phong cảnh trong GTSDB ---
print("\n--- Chạy thử nghiệm hàm recognize_traffic_signs_in_scene ---")

# Lấy danh sách tất cả các file .ppm trong TRAIN_DIR
all_ppm_files = [f for f in os.listdir(TEST_DIR) if f.endswith('.ppm')]

if not all_ppm_files:
    print(f"Lỗi: Không tìm thấy file .ppm nào trong thư mục {TRAIN_DIR}")
else:
    # Chọn ngẫu nhiên một file ảnh để kiểm tra
    random_test_image_filename = choice(all_ppm_files)
    random_test_image_path = os.path.join(TEST_DIR, random_test_image_filename)

    # Gọi hàm chính để phát hiện và nhận diện
    detected_signs, recognized_labels, detection_scores = recognize_traffic_signs_in_scene(random_test_image_path)

    print("\n--- Kết quả tổng hợp cuối cùng ---")
    if detected_signs:
        for i, (box, label, score) in enumerate(zip(detected_signs, recognized_labels, detection_scores)):
            # Display the shifted score, or you could reverse the shift if you want the original decision_function score
            print(f"Biển báo {i+1}: Vị trí = {box}, Nhãn = '{label}', Điểm phát hiện (shifted for NMS) = {score:.2f}")
    else:
        print("Không tìm thấy biển báo nào trong ảnh.")

import cv2
import numpy as np
import matplotlib.pyplot as plt

def visualize_segmentation_hsv(image_path):
    img_bgr = cv2.imread(image_path)
    if img_bgr is None:
        print("Không tìm thấy ảnh!")
        return
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    # 1. Chuyển sang HSV và Cân bằng sáng (CLAHE) trên kênh Value (V)
    hsv = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2HSV)
    h, s, v = cv2.split(hsv)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    v_eq = clahe.apply(v)
    hsv_eq = cv2.merge((h, s, v_eq)) # Gộp lại

    # 2. Tạo Binary Mask (Ảnh b)
    # Lọc Đỏ (Hue 0-10 và 160-180)
    lower_red1 = np.array([0, 70, 50])
    upper_red1 = np.array([10, 255, 255])
    lower_red2 = np.array([160, 70, 50])
    upper_red2 = np.array([180, 255, 255])

    # Lọc Xanh dương (Hue 100-130)
    lower_blue = np.array([100, 70, 50])
    upper_blue = np.array([130, 255, 255])

    mask_red1 = cv2.inRange(hsv_eq, lower_red1, upper_red1)
    mask_red2 = cv2.inRange(hsv_eq, lower_red2, upper_red2)
    mask_blue = cv2.inRange(hsv_eq, lower_blue, upper_blue)

    # Gộp các mask lại (Dùng toán tử Bitwise OR)
    raw_binary_mask = mask_red1 | mask_red2 | mask_blue

    # 3. Tạo Filtered Mask (Ảnh c)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    filtered_mask = cv2.morphologyEx(raw_binary_mask, cv2.MORPH_CLOSE, kernel)
    filtered_mask = cv2.morphologyEx(filtered_mask, cv2.MORPH_OPEN, kernel)

    contours, _ = cv2.findContours(filtered_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    final_clean_mask = np.zeros_like(filtered_mask)

    for c in contours:
        x, y, w, h = cv2.boundingRect(c)
        area = w * h
        aspect_ratio = float(w) / h

        # ÁP DỤNG THÔNG SỐ TỪ BÀI BÁO (Area & Ratio)
        if 200 < area < 16000 and 0.4 < aspect_ratio < 1.9:
            cv2.drawContours(final_clean_mask, [c], -1, 255, thickness=-1)

    # Vẽ biểu đồ
    plt.figure(figsize=(18, 6))

    plt.subplot(1, 3, 1)
    plt.imshow(img_rgb)
    plt.title('(a) Original Image', fontsize=14)
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(raw_binary_mask, cmap='gray')
    plt.title('(b) Binary Image (Mask thô)', fontsize=14)
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(final_clean_mask, cmap='gray')
    plt.title('(c) Filtered Image (Đã lọc rác)', fontsize=14)
    plt.axis('off')

    plt.tight_layout()
    plt.show()

# Hãy test với bức ảnh xe tải hoặc bức ảnh tối (00307.ppm)
visualize_segmentation_hsv(TEST_DIR +  '00100.ppm')

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from random import choice

def visualize_segmentation_rgb_normalized(image_path):
    img_bgr = cv2.imread(image_path)
    if img_bgr is None:
        print(f"Không tìm thấy ảnh tại {image_path}!")
        return

    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    image_height, image_width, _ = img_rgb.shape

    # =======================================================
    # CHIẾN THUẬT 4: TIỀN XỬ LÝ ÁNH SÁNG BẰNG CLAHE
    # =======================================================
    lab = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.5, tileGridSize=(8, 8))
    l_eq = clahe.apply(l)
    img_enhanced = cv2.cvtColor(cv2.merge((l_eq, a, b)), cv2.COLOR_LAB2RGB)

    # =======================================================
    # CHIẾN THUẬT 5: TOÁN HỌC NORMALIZED RGB R/(R+G+B)
    # =======================================================
    R = img_enhanced[:,:,0].astype(np.float32)
    G = img_enhanced[:,:,1].astype(np.float32)
    B = img_enhanced[:,:,2].astype(np.float32)
    Sum = R + G + B + 1e-6

    norm_R = R / Sum
    norm_B = B / Sum

    red_mask = np.uint8((norm_R > 0.40) & (R > 30)) * 255
    blue_mask = np.uint8((norm_B > 0.40) & (B > 30)) * 255

    # Raw Binary Mask (Ảnh b)
    raw_binary_mask = cv2.bitwise_or(red_mask, blue_mask)

    # Dùng hình thái học Morphological (Close/Open) để nối liền các mảng màu bị rách
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    filtered_mask = cv2.morphologyEx(raw_binary_mask, cv2.MORPH_CLOSE, kernel)
    filtered_mask = cv2.morphologyEx(filtered_mask, cv2.MORPH_OPEN, kernel)

    # =======================================================
    # CHIẾN THUẬT 2: LỌC RÁC THEO HÌNH HỌC (SHAPE-BASED)
    # =======================================================
    contours, _ = cv2.findContours(filtered_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    final_clean_mask = np.zeros_like(filtered_mask) # Để vẽ các contour đã lọc
    num_boxes = 0
    for c in contours:
        x, y, w, h = cv2.boundingRect(c)
        area = w * h
        aspect_ratio = float(w) / h

        if 200 < area < 16000 and 0.4 < aspect_ratio < 1.9:
            cv2.drawContours(final_clean_mask, [c], -1, 255, thickness=-1) # Vẽ contour lên mask cuối cùng
            num_boxes += 1

    # Vẽ biểu đồ
    plt.figure(figsize=(18, 6))

    plt.subplot(1, 3, 1)
    plt.imshow(img_rgb)
    plt.title('(a) Original Image', fontsize=14)
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(raw_binary_mask, cmap='gray')
    plt.title('(b) Raw Binary Mask (RGB Normalized)', fontsize=14)
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(final_clean_mask, cmap='gray')
    plt.title(f'(c) Filtered Mask ({num_boxes} boxes)', fontsize=14)
    plt.axis('off')

    plt.tight_layout()
    plt.show()

    print(f"Đã trực quan hóa phân đoạn RGB Normalized cho ảnh: {os.path.basename(image_path)}")


visualize_segmentation_rgb_normalized(TEST_DIR +  '00101.ppm')