def get_class_names():
    """
    Ánh xạ nhãn 0-42 sang tên biển báo.
    """
    return {
    0: 'Giới hạn tốc độ (20km/h)', 
    1: 'Giới hạn tốc độ (30km/h)', 
    2: 'Giới hạn tốc độ (50km/h)',
    3: 'Giới hạn tốc độ (60km/h)', 
    4: 'Giới hạn tốc độ (70km/h)', 
    5: 'Giới hạn tốc độ (80km/h)',
    6: 'Hết giới hạn tốc độ (80km/h)', 
    7: 'Giới hạn tốc độ (100km/h)', 
    8: 'Giới hạn tốc độ (120km/h)',
    9: 'Cấm vượt', 
    10: 'Cấm vượt xe trên 3.5 tấn', 
    11: 'Ưu tiên tại giao lộ',
    12: 'Đường ưu tiên', 
    13: 'Nhường đường', 
    14: 'Dừng lại', 
    15: 'Cấm xe cộ',
    16: 'Cấm xe trên 3.5 tấn', 
    17: 'Cấm vào', 
    18: 'Cảnh báo chung',
    19: 'Đường cong nguy hiểm bên trái', 
    20: 'Đường cong nguy hiểm bên phải', 
    21: 'Đường cong kép',
    22: 'Đường gồ ghề', 
    23: 'Đường trơn trượt', 
    24: 'Đường hẹp dần bên phải',
    25: 'Công trường', 
    26: 'Đèn giao thông', 
    27: 'Người đi bộ', 
    28: 'Trẻ em qua đường',
    29: 'Xe đạp qua đường', 
    30: 'Cẩn thận băng/tuyết', 
    31: 'Động vật hoang dã qua đường',
    32: 'Hết giới hạn tốc độ và cấm vượt', 
    33: 'Rẽ phải phía trước', 
    34: 'Rẽ trái phía trước',
    35: 'Chỉ được đi thẳng', 
    36: 'Đi thẳng hoặc rẽ phải', 
    37: 'Đi thẳng hoặc rẽ trái',
    38: 'Đi bên phải', 
    39: 'Đi bên trái', 
    40: 'Bắt buộc đi vòng xuyến',
    41: 'Hết cấm vượt', 
    42: 'Hết cấm vượt xe trên 3.5 tấn'
}
